- match definition of parity function to sgn0 of ietf draft in swu map
w3f/arkworks-algebra pull request #33
Opened 2022-01-12 09:09 UTC by drskalman

- adapt unit tests to the new definition

## Description

closes: #XXXX

---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [ ] Targeted PR against correct branch (master)
- [ ] Linked to Github issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Wrote unit tests
- [ ] Updated relevant documentation in the code
- [ ] Added a relevant changelog entry to the `Pending` section in `CHANGELOG.md`
- [ x ] Re-reviewed `Files changed` in the Github PR explorer

2022-01-12 09:42 UTC, InaOana reviewed
From my side, code and tests match the sig0 ieft draft.

2022-01-12 09:54 UTC, mmagician requested changes

2022-01-12 09:54 UTC, mmagician commented on ec/src/hashing/curve_maps/swu/mod.rs
> +        assert_eq!(Fq6::parity(&element_test1), true, "parity is the oddness of first none-zero coefficient of element represented over the prime field");
```suggestion
        assert_eq!(Fq6::parity(&element_test1), true, "parity is the oddness of first non-zero coefficient of element represented over the prime field");
```

2022-01-12 09:54 UTC, mmagician commented on ec/src/hashing/curve_maps/swu/mod.rs
> +        assert_eq!(Fq6::parity(&element_test2), true, "parity is the oddness of first none-zero coefficient of element represented over the prime field");
```suggestion
        assert_eq!(Fq6::parity(&element_test2), true, "parity is the oddness of first non-zero coefficient of element represented over the prime field");
```

2022-01-12 09:54 UTC, mmagician commented on ec/src/hashing/curve_maps/swu/mod.rs
> +        assert_eq!(Fq2::parity(&element_test1), true, "parity is the oddness of first none-zero coefficient of element represented over the prime field" );
```suggestion
        assert_eq!(Fq2::parity(&element_test1), true, "parity is the oddness of first non-zero coefficient of element represented over the prime field" );
```

2022-01-12 18:18 UTC, Pratyush commented on ec/src/hashing/curve_maps/swu/mod.rs
> +        }
```suggestion
            .find(|&x| !x.is_zero())
            .map_or(false, |x| x.into_repr().is_odd())
```

2022-01-12 18:19 UTC, Pratyush commented on ec/src/hashing/curve_maps/swu/mod.rs
> +        match element
```suggestion
        element
```

2022-01-12 18:19 UTC, Pratyush approved these changes

2022-01-13 08:24 UTC, mmagician approved these changes

2022-01-13 08:24 UTC, merged